### ISSUE TITLE
About Your Thesis

### ISSUE THREAD

**Issue by bseker** [Sawchord/anthocnet#2]
hi Sawchord,

You mentioned that you used anthocnet in your thesis.  Is there any way to reach your thesis? İf possible, I would like to.

Thanks a lot,
Burak

**Comment by Sawchord** [comment]
Hello Burak,

I can't find the Version of the Thesis which I submitted for some reason. However I can provide you with a Version I had backed up a week before submission. I did not change any content, it just has a lot of typos :roll_eyes: 

Just provide me with an E-Mail address or another way to get into contact with you.

Regarding the code:  It seems to be broken with newer versions of NS3.
I used NS3.26 for my thesis.
I am not maintaining or updating the code in any way, just hosting it in case it might be useful for someone.

**Comment by bseker** [comment]
Hello again.

Sorry for replying so late, the days of corona is a bit chaotic for me.

Even a draft would be good if you can send it to mutluseker33@gmail.com .

Btw, I noticed the notes you mentioned regarding to code, still I benefit a lot from it. Thanks for sharing :)

Have a great day,
Best regards.

Burak

> Hello Burak,
> 
> I can't find the Version of the Thesis which I submitted for some reason. However I can provide you with a Version I had backed up a week before submission. I did not change any content, it just has a lot of typos 🙄
> 
> Just provide me with an E-Mail address or another way to get into contact with you.
> 
> Regarding the code: It seems to be broken with newer versions of NS3.
> I used NS3.26 for my thesis.
> I am not maintaining or updating the code in any way, just hosting it in case it might be useful for someone.

**Comment by Sawchord** [comment]
Send you the thesis.
Closing Issue
